apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hejtado-quido-ingress
spec:
  rules:
  - host: hejtado.home
    http:
      paths:
      - path: /api/v1/quido
        backend:
          serviceName: hejtado-quido-service
          servicePort: 80