apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hejtado
  name: hejtado-quido-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*.home"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hejtado-quido-service
                port:
                  number: 80